### ISSUE TITLE
Can we get delegate call of PayNow button tapped?

### ISSUE THREAD

**Issue by cwinUser** [realexpayments/rxp-ios#6]
Is it possible to have access of Pay Now button tap action , using iFrames of realex integration.

**Comment by rxp-developers** [comment]
Hi @cwinUser,

I don't believe so,. The Pay Now button is on the HPP, which is loaded inside the WKWebView and as far as my understanding goes, you can't delegate from actions inside a WKWebView.

@slogsdon, could you please confirm whether this is the case?

@cwinUser, what functionality are you trying to achieve?

Best,

Seán

**Comment by slogsdon** [comment]
Hey Sean,

This should be possible with more work on both the iOS library as well as the hosted HPP code. WKWebViews allow for JavaScript <-> native code communication which should allow us to expose events from the HPP to the app's native code.

We would need to do some research into what functionality/events we want to expose so that work can be prioritized and scheduled.

/cc @rxp-developers

**Comment by RealexITSO** [comment]
Thanks @slogsdon, we can look at scoping the work for the library and HPP.
